Added logic to have codebuild pipeline fail if a docker image already eixsts with the same tag as the project's version as specified in the POM

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,6 +1,7 @@
 version: 0.2
 
 env:
+  shell: bash
   # These secrets come from Secrets Manager Parameter Store.
   parameter-store:
     DOCKERHUB_TOKEN:  DOCKERHUB_TOKEN
@@ -28,12 +29,18 @@ phases:
       # Get project's version from pom.xml.
       - PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
 
-      # Copy custom maven settings from S3 bucket.
-      - aws s3 cp s3://maven-build-settings/qb4j_settings.xml /root/.m2/settings.xml
-
-      # Check if the image exists in docker hub already.
+      # Check if the image exists in docker hub already.  If the image tag matches the project's version from the POM,
+      # then exit/fail the build.
       - IMAGE_EXISTS=$(docker pull joneschris/qb4j-mvc:"$PROJECT_VERSION" > /dev/null && echo "true" || echo "false")
       - echo "Does the image exist?  $IMAGE_EXISTS"
+      - |
+        if [ "$IMAGE_EXISTS" == "true" ]; then
+          echo "The image, $PROJECT_VERSION, already exists.  You probably need to bump the project's version in the pom.xml."
+          exit 1
+        fi
+
+      # Copy custom maven settings from S3 bucket.
+      - aws s3 cp s3://maven-build-settings/qb4j_settings.xml /root/.m2/settings.xml
 
   build:
     commands:
